---
- name: Ping all hosts
  hosts: all #play毎に実行するNodeの選択にpatternを適用可能 
  # https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html#common-patterns
  # serial: 1 # 並列実行数を決められる
  roles:
    - ping
    - jinja

- name: Ping only group1 hosts
  hosts: all #play毎に実行するNodeの選択にpatternを適用可能 
  roles:
    - { role: ping, when: "'group1' in group_names" }
