- name: Add some users with dict
  hosts: all_hosts
  tasks:
  - name: Using dict2items
    ansible.builtin.debug:
      msg: "{{item.key}} : {{item.value}}"
    loop: "{{tag_data | dict2items}}"
    vars:
      tag_data:
        Environment: dev
        Application: payment