- name: Tasks with Nested loop
  hosts: all_hosts
  tasks:
  - name: Register loop output as a variable
    ansible.builtin.shell:
      "echo user:{{item[0]}}, db:{{item[1]}}"
    loop:
      "{{ ['alice', 'bob'] | product(['clientDb', 'employeedb', 'providerDb'] | list)   }}"
    register: echo
# register変数にresults fiealdがあり，内部にlistとして各loopの結果が格納される
  - name: Check command result
    ansible.builtin.debug:
      var: echo
    when: item.rc != 0
    loop: "{{ echo.results  }}"