- name: Update web servers
  hosts: all_hosts
  remote_user: root
  tasks:
  - name:  Ensure apache is at the latest version
    ansible.builtin.yum:
      name:
        - httpd
      state: latest
  - name: Write the apache config file
    ansible.builtin.template:
      src: /srv/httpd.j2
      dest: /etc/http.conf