- name: Check differences between two files
  command: diff /tmp/test.txt /tmp/test.txt
  register: diff_result
  ignore_errors: true

- name: Set changed status based on diff result
  debug:
    msg: >
      {% if diff_result.rc == 0 %}
        The files are identical.
      {% else %}
        The files are different.
      {% endif %}
  changed_when: diff_result.rc != 0
