# that paramで与えたexpressionをassertionする
- name: Assert module
  ansible.builtin.assert:
    that: "'group1' in group_names"

# 接続できるか検証
- name: Wait 
  ansible.builtin.wait_for_connection:
    delay: 1
    timeout: 10

